name = "transpsaude"
compatibility_date = "2026-03-20"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "transpsaude-db"
database_id = "a705c477-c28e-4045-91e3-95750e686623"
